services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  fastapi_app:
    build:
      context: .
    container_name: fastapi_app
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

  stream_consumer:
    build:
      context: .
    container_name: stream_consumer
    depends_on:
      - fastapi_app
    environment:
      - REDIS_HOST=redis
    command: ["python", "stream_consumer.py"]
